MV-Dist-Info:
  Monitoring_Visit__c:
    Date__c: Date
    Monitor__c: Name
    Visiting_structure__c: Structure
    School__c: School
    CPP_in_place__c: CPP
    CPP_posted__c: CPP_placing
    TM_in_place__c: TM
    TM__c: TM_Name
    People_met__c: Meet
    Documents_reviewed__c: Docs
    SNF_received__c: SNF
    Amount__c: SNF_Amount
    SNF_Receipts__c: SNF_Receipt
    SNF_Signatures__c: SNF_Signature
    SNF_recipients_met__c: SNF_Talk
    Number_met__c: SNF_Talk_No
    Fee_payments_match__c: Fee_Payment_Conf
    Bank_statements__c: Bank_Statement
    SNF_verified__c: Bank_Statement_SNF
    Bursary_verified__c: Bank_Statement_Bursary
    Expenses_match_records__c: Bank_Statements_Match

MV-Dist-Info5:
  Monitoring_Visit__c:
    Date__c: Date
    Monitor__c: Name
    Monitor_Name__c: Name
    Visiting_structure__c: Structure
    School__c: School
    CPP_in_place__c: CPP
    CPP_posted__c: CPP_placing
    Amount__c: SNF_Amount
    TM__c: TM_Name
    TM_Name__c: TM_Name
  Financial_Accountability__c:
    School__c: School
    Notes__c: FM_FollowUp_Notes
  Structure__c:
    School__c: School
    Group_Name__c: MSG_Name 
    MSG_active__c: MSG_Contact
    Initiative__c: MSG_Activity
  # Child_Protection__c:
  #   School__c: School
  #   steps_taken_by_school__c: Abuse_school_action
  #   Steps_taken_by_school__c: Abuse_CDC_Action
  #   Notes__c: Abuse_Notes