require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ObjectMappingsController do
  describe 'new' do
    it 'should populate survey and object mapping' do
      survey = EpiSurveyor::Survey.new
      EpiSurveyor::Survey.should_receive(:find).with("1").and_return(survey)
      get :new, :survey_id => "1"
      response.should be_success
      assigns[:survey].should == survey
      assigns[:object_mapping].should_not be nil
      assigns[:sf_object_types].should have(4).things
    end
  end
  
  describe 'create' do
    it 'should create the mapping' do
      post :create, :object_mapping => {:survey_id => 1, :sf_object_type => "Monitoring_Visit__c"}
      assigns[:object_mapping].survey_id.should == 1
      assigns[:object_mapping].sf_object_type.should == "Monitoring_Visit__c"
      response.should redirect_to new_object_mapping_field_mapping_path(assigns[:object_mapping])
    end
    
    it 'should reuse an existing mapping' do
      params = {:object_mapping => {:survey_id => 1, :sf_object_type => "Monitoring_Visit__c"}}
      ObjectMapping.create(params[:object_mapping])
      post :create, params
      ObjectMapping.where(params[:object_mapping]).should have(1).things
      response.should redirect_to new_object_mapping_field_mapping_path(assigns[:object_mapping])
    end
  end
  
  describe 'update' do
    it 'should update a record when it exists' do
      params = {:object_mapping => {:field_mappings_attributes => {
                                      "0" => {:field_name => "a_field", :question_name => 'a_question'},
                                      "1" => {:field_name => "b_field", :question_name => ''}
                                      }
                                    }
                }

      mapping = ObjectMapping.create(:survey_id => 1, :sf_object_type => 'AnObject')
      put :update, :id => mapping.id, :object_mapping => params[:object_mapping]
      mapping.reload
      mapping.field_mappings.first.field_name.should == 'a_field'
      mapping.field_mappings.should have(1).things
    end
  end
  
end
